// For champions list component
export const FETCH_CHAMPIONS_DATA = 'CHAMPIONS/FETCH_CHAMPIONS_DATA'
export const SET_CURRENT_PAGE = 'CHAMPIONS/SET_CURRENT_PAGE'
export const SET_PER_PAGE = 'CHAMPIONS/SET_PER_PAGE'
export const SET_SORT_VALUE = 'CHAMPIONS/SET_SORT_VALUE'
export const SET_SEARCH_VALUE = 'CHAMPIONS/SET_SEARCH_VALUE'

// For items list component
export const FETCH_ITEMS_DATA = 'ITEMS/FETCH_ITEMS_DATA'
export const SET_CURRENT_ITEMS_PAGE = 'ITEMS/SET_CURRENT_ITEMS_PAGE'
export const SET_ITEMS_PER_PAGE = 'ITEMS/SET_ITEMS_PER_PAGE'
